name: Datalab

on:
  push:
    branches: [ datalab ]
  pull_request:
    branches: [ datalab ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab make

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Make tests
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab make test

  grades:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2
    - name: Make tests
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab make tests
    - name: Make grades
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab make grade
