name: Datalab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab /bin/sh make test
    - name: Make grades
      run: |
        docker run -v ${{ github.workspace }}:/home \
            -w /home/labs/datalab/ \
            xcancerberox/orga:datalab /bin/sh make grades
